 CREATE TABLE Invoices (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  projectId BIGINT NOT NULL,
  clientId BIGINT NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  dueDate DATE NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  invoiceNumber VARCHAR(50) NOT NULL UNIQUE,
  pdfUrl TEXT
  );